### ISSUE TITLE
Project 2 Example Solution

### ISSUE THREAD

**Issue by s2t2** [prof-rossetti/georgetown-opim-243-201901#42]
As an instructor (graduate assistant), I should submit a solution for project 2, in order to better prepare to help students with this project and grade it.

**Comment by s2t2** [comment]
(sorry closed by accident)

**Comment by s2t2** [comment]
FYI: I have posted my solution! 😸

**Comment by hiepnguyen034** [comment]
I just posted my pandas solution too 👍

**Comment by s2t2** [comment]
Ok, want to submit a PR?

**Comment by hiepnguyen034** [comment]
I already added the github repos to the submission.csv file.

**Comment by s2t2** [comment]
Oh I see you made a direct commit. That's ok. In the future I'd prefer for you to work on a branch and submit a PR for my review. Thanks!

**Comment by s2t2** [comment]
Nice job, and thanks 🙏
